---
title: "Research 3/1/3033"
author: "Grace Rade"
date: "3/1/2022"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
```

```{r}
mort_data <- read.delim("CompressedMortality_1999_2016.txt")
```

```{r}
black_male_mort <- mort_data %>% 
  filter(Race == "Black or African American", Gender.Code =="M") %>% 
  group_by(State, Year) %>% 
  summarise(black_male_mortality = (Deaths/Population) * 100000)
```

```{r}
black_female_mort <- mort_data %>% 
  filter(Race == "Black or African American", Gender.Code =="F") %>% 
  group_by(State, Year) %>% 
  summarise(black_female_mortality = (Deaths/Population) * 100000)
```

```{r}
white_male_mort <- mort_data %>% 
  filter(Race == "White", Gender.Code =="M") %>% 
  group_by(State, Year) %>% 
  summarise(white_male_mortality = (Deaths/Population) * 100000)
```

```{r}
white_female_mort <- mort_data %>% 
  filter(Race == "White", Gender.Code =="F") %>% 
  group_by(State, Year) %>% 
  summarise(white_female_mortality = (Deaths/Population) * 100000)
```

```{r}
white_mort <- white_male_mort %>% 
  left_join(white_female_mort, by = c("State", "Year"))
```

```{r}
black_mort <- black_male_mort %>% 
  left_join(black_female_mort, by = c("State", "Year"))
```

```{r}
all_mort <- black_mort %>% 
  full_join(white_mort, by = c("State", "Year"))
```

```{r}
export(all_mort, file = 'all_mort.csv')
```

Mortality Data (CDC Wonder) 