---
title: "Research Spring Break"
author: "Grace Rade"
date: "3/17/2022"
output: html_document
---
```{r}
library(tidyverse)
library(rio)
```

# Borrow the code from my last weighted mortality rates to join the data sets together
```{r}
mort_1979 <- import("CompressedMortality1979_1998_22.txt")
mort_1999 <- import("CompressedMortality1999_2016_2copy2.txt")

mort_hispanic <- read.delim("Compressed Mortality, 1999-2016copy.txt") %>% 
  filter(Hispanic.Origin == "Hispanic or Latino") %>% 
  rename(Race = Hispanic.Origin, Race.Code = Hispanic.Origin.Code)
mort_1979_race <-  read.delim("CompressedMortality1979-1998.txt")
mort_1999_race <- read.delim("CompressedMortality_1999_2016.txt")

mort_hispanic$Population <- as.numeric(mort_hispanic$Population)

total_state_mort <- mort_1979 %>% 
  full_join(mort_1999, by = c("State", "Year", "Population", "Deaths")) %>% 
  select(State, Year, Population, Deaths) %>% 
  rename(State_Population = Population, State_Deaths = Deaths)

mort_race <- mort_1979_race %>%
  full_join(mort_1999_race, by = c("State", "Year", "Population", "Deaths", "Race", "Gender.Code"))

mort_race <- mort_race %>% 
  full_join(mort_hispanic, by = c("State", "Year", "Population", "Deaths", "Race", "Gender.Code")) %>% 
  select(State, Year, Gender.Code, Race, Population, Deaths) %>% 
  rename(Group_Population = Population)

mort_state_race <- mort_race %>% 
  full_join(total_state_mort, by = c("State", "Year")) %>%
  filter(Race == "Black or African American" | Race == "Hispanic or Latino" | Race == "White") %>% 
  rename(Group_Deaths = Deaths)
```

#Same methods as before but this time do a different stat to weight by (deaths proportion = (group deaths/state deaths)), keeping the old weighted mortality rate though
```{r}
# Black mortality

black_male_mort <- mort_state_race %>% 
  filter(Race == "Black or African American", Gender.Code == "M") %>% 
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), black_male_mortality = (Group_Deaths/State_Population) * 100000, black_male_mortality_weighted = black_male_mortality/population_proportion, black_male_mortality_weighted_2 = black_male_mortality*deaths_proportion)

black_female_mort <- mort_state_race %>% 
  filter(Race == "Black or African American", Gender.Code == "F") %>% 
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), black_female_mortality = (Group_Deaths/State_Population * 100000), black_female_mortality_weighted = black_female_mortality/population_proportion, black_female_mortality_weighted2 = black_female_mortality*deaths_proportion)

black_mort <- black_male_mort %>% 
  full_join(black_female_mort, by = c("State", "Year", "Gender.Code", "Race", "population_proportion", "deaths_proportion", "Group_Population", "State_Population", "Group_Deaths", "State_Deaths"))
```

```{r}
#White mortality

white_male_mort <- mort_state_race %>% 
  filter(Race == "White", Gender.Code == "M") %>% 
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), white_male_mortality = (Group_Deaths/State_Population) * 100000, white_male_mortality_weighted = (white_male_mortality/population_proportion), white_male_mortlaity_weighted2 = (white_male_mortality*deaths_proportion))

white_female_mort <- mort_state_race %>% 
  filter(Race == "White", Gender.Code == "F") %>% 
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), white_female_mortality = (Group_Deaths/State_Population) * 100000, white_female_mortality_weighted = white_female_mortality/population_proportion, white_female_mortality_weighted2 = white_female_mortality*deaths_proportion)

white_mort <- white_male_mort %>% 
  full_join(white_female_mort, by = c("State", "Year", "Gender.Code", "Race", "population_proportion", "deaths_proportion", "Group_Population", "State_Population", "Group_Deaths", "State_Deaths"))
```

```{r}
#Hispanic mortality
hispanic_male_mort <- mort_state_race %>% 
  filter(Race == "Hispanic or Latino", Gender.Code == "M") %>%
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), hispanic_male_mortality = (Group_Deaths/State_Population) * 100000, hispanic_male_mortality_weighted = hispanic_male_mortality/population_proportion, hispanic_male_mortality_weighted2 = hispanic_male_mortality*deaths_proportion)

hispanic_female_mort <- mort_state_race %>% 
  filter(Race == "Hispanic or Latino", Gender.Code == "F") %>% 
  group_by(State, Year) %>% 
  mutate(population_proportion = (Group_Population/State_Population), deaths_proportion = (Group_Deaths/State_Deaths), hispanic_female_mortality = (Group_Deaths/State_Population) * 100000, hispanic_female_mortality_weighted = hispanic_female_mortality/population_proportion, hispanic_female_mortality_weighted2 = hispanic_female_mortality*deaths_proportion)

hispanic_mort <- hispanic_male_mort %>% 
  full_join(hispanic_female_mort, by = c("State", "Year", "Gender.Code", "Race", "population_proportion", "deaths_proportion", "Group_Population", "State_Population", "Group_Deaths", "State_Deaths"))
```

#Join everything back together
```{r}
full_morts <- black_mort %>% 
  full_join(hispanic_mort, by = c("State", "Year", "Gender.Code", "Race", "population_proportion", "deaths_proportion", "Group_Population", "State_Population", "Group_Deaths", "State_Deaths"))

full_morts <- full_morts %>% 
  full_join(white_mort, by = c("State", "Year", "Gender.Code", "Race", "population_proportion", "deaths_proportion", "Group_Population", "State_Population", "Group_Deaths", "State_Deaths"))
```

```{r}
export(full_morts, "full_morts.csv")
```

